name: Android CI

on:
  push:
    branches: [ main, develop, "feature/**", "feat/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '18'
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Build Dev Debug (skip lint)
        run: ./gradlew :app:assembleDevDebug -x lint
      - name: Lint (advice only)
        run: ./gradlew :app:lintDevDebug || true
      - name: Unit tests (local, fast)
        run: ./gradlew :app:testDevDebugUnitTest || true


